### PR TITLE
Fix shading

### PR DESCRIPTION
**Pull request by lifebarier**
Seems to fix shading issue #310 #316

### CODE REVIEW

**Comment by Stewori** [comment]
Thank you for this work. The fix looks good to me and makes sense to me. It did not occur to me that a `module-info` file is in the game because it is so well hidden and not present in source.
Have you signed the [CLA](https://jython-devguide.readthedocs.io/en/latest/coredev.html#sign-a-contributor-agreement)?
Also, please feel free to add yourself to ACKNOWLEDGMENTS (unless you are already in the list).

**Comment by lifebarier** [comment]
Just signed CLA. I will skip ACKNOWLEDGMENTS file for now.

**Comment by Stewori** [comment]
Alright. (We may still record your contribution in ACKNOWLEDGMENTS eventually by means of https://github.com/jython/jython/pull/308, I hope that's okay for you.)

**Comment by Stewori** [comment]
@juniartisu Does this fix work for you as well?/Can you confirm it fixes #316 in your environment?

**Comment by juniartisu** [comment]
@Stewori I will try out the fix and do testing on it and will put update here once it is done.

**Comment by juniartisu** [comment]
@Stewori The fix is good. I am not seeing any issue so far. Than you @lifebarier for investigating and fixing it.

**Comment by Stewori** [comment]
@lifebarier could you do me a favor and add the line
`    - [ GH-316 ] PR313 cause regression`
to the NEWS file (line 22) as part of this PR? Then I wouldn't have to make a separate PR for that. When done, I will merge this PR. Thanks again!

**Comment by abhi-rck** [comment]
@lifebarier @Stewori 
i tried to build the jar with ant after this fix. Though the shading is done properly but still i see errors when i am trying to decompile the built jar with Java Decompiler jd-gui-1.6.6.jar. 
this error indicate incomplete or corrupted jar. 

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 9
        at com.sun.nio.zipfs.ZipConstants.SH(ZipConstants.java:192)
        at com.sun.nio.zipfs.ZipConstants.LG(ZipConstants.java:196)
        at com.sun.nio.zipfs.ZipFileSystem$Entry.readExtra(ZipFileSystem.java:2302)
        at com.sun.nio.zipfs.ZipFileSystem$Entry.cen(ZipFileSystem.java:1903)
        at com.sun.nio.zipfs.ZipFileSystem$Entry.readCEN(ZipFileSystem.java:1871)
        at com.sun.nio.zipfs.ZipFileSystem.getEntry0(ZipFileSystem.java:1329)
        at com.sun.nio.zipfs.ZipFileSystem.getFileAttributes(ZipFileSystem.java:317)
        at com.sun.nio.zipfs.ZipPath.getAttributes(ZipPath.java:664)
        at com.sun.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:294)
        at java.nio.file.Files.readAttributes(Files.java:1737)
        at java.nio.file.Files.isDirectory(Files.java:2192)
        at org.jd.gui.model.container.GenericContainer$Entry.isDirectory(GenericContainer.java:110)
        at org.jd.gui.model.container.ContainerEntryComparator.compare(ContainerEntryComparator.java:26)

**Comment by lifebarier** [comment]
@abhi-rck 
Why are you trying to decompile jar?
I would be really surprised if change to exclude 2 module-info files from build would break jar in such way.
Anyhow, for fun I tired to open jython-standalone.jar with that decompiler and it opened just fine.

**Pull request merged**
