### PR TITLE
fix(PrePy): JavaWebStart compatibility restored

### LINKED ISSUE #57: JavaWebStart compatibilty broken in 2.7.2
The current implementation fails when instantiating a PythonInterpreter with the error:

> Exception in thread "main" java.lang.IllegalArgumentException: URI scheme is not "file"
	at java.io.File.<init>(File.java:421)
	at org.python.core.PrePy.getJarFileNameFromURL(PrePy.java:427)
	at org.python.core.PrePy._getJarFileName(PrePy.java:362)
	at org.python.core.PrePy.getJarFileName(PrePy.java:345)
	at org.python.core.PySystemState.doInitialize(PySystemState.java:1195)
	at org.python.core.PySystemState.initialize(PySystemState.java:1130)
	at org.python.core.PySystemState.initialize(PySystemState.java:1085)
	at org.python.core.PySystemState.initialize(PySystemState.java:1080)
	at org.python.core.PySystemState.initialize(PySystemState.java:1075)
	at org.python.core.PySystemState.initialize(PySystemState.java:1070)
	at org.python.core.ThreadStateMapping.getThreadState(ThreadStateMapping.java:56)
	at org.python.core.Py.getThreadState(Py.java:1741)
	at org.python.core.Py.getThreadState(Py.java:1737)
	at org.python.core.Py.getSystemState(Py.java:1757)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:100)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:93)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:70)

This used to work in Jython 2.5.3

The reason is that when running Jython in JavaWebStart, the resources URLs when calling class.getResource(string) are of the form:

    jar:http://server:8080/signedWebApp/jython-slim-2.7.3a1.jar!/org/python/core/PrePy.class

This is not handled correctly by the current implementation.

### PR DESCRIPTION
**Pull request by SchwingSK**
Fixes #57

### CODE REVIEW

**Comment by jeff5** [comment]
Thanks for fixing this (and to @hansiang93 for confirming). I'd like to use this in 2.7.3, but you'd have to sign the Python CLA. There are two steps:

- [ ] create an account at the **_CPython_** bug tracker https://bugs.python.org/, if you don't have one already, giving it your GitHub name, then
- [ ] this form: https://www.python.org/psf/contrib/contrib-form/

Sorry for the paperasse. After an office-hours delay, [this gadget](https://check-python-cla.herokuapp.com/) will know you by your GitHub name.

**Comment by SchwingSK** [comment]
CLA signed, glad this will be merged in 2.7.3 :)

**Comment by Stewori** [comment]
@SchwingSK would you help maintaining NEWS by adding GH-57 to the bugs-fixed-in-2.7.3-section? Also, please add yourself to the contributors list in ACKNOWLEDGMENTS (unless you bother being remembered). Thanks!

**Comment by jeff5** [comment]
@Stewori : I can do that and push to the PR's branch ... if I don't mess it up! Then I think squash & merge is appropriate (which I hope will credit the author, not me).

**Comment by Stewori** [comment]
@jeff5 Ah, sorry I totally forgot about this PR after my last comment. Please feel free to move on with it however you like.

**Comment by jeff5** [comment]
Ok, that seems to have given credit where it is due, in the [squashed commit](https://github.com/jython/jython/commit/7a073156587066e1e39121156b70c5a80e6b4756).

I cancelled the regression tests here because I know they will run again on the actual commit to master, and not much can have gone wrong in updating NEWS.

**Pull request merged**
