### PR TITLE
Fix issue #245 document downloads in README.md

### PR DESCRIPTION
**Pull request by clach04**

### CODE REVIEW

**Comment by Stewori** [comment]
Please port the fix to readme.txt as well. Also feel free to add yourself to the contributors list (if not yet done).

**Comment by clach04** [comment]
@Stewori posted additional, commits. May be worth squashing on merge?

**Comment by jeff5** [comment]
Thanks for this @clach04 and @Stewori for responding. I'll resolve conflicts, add to NEWS and, yes, squash-merge.

**Comment by jeff5** [comment]
@clach04: I notice you have a contribution to CPython
https://github.com/python/cpython/commit/be55d99b3d0d289b2948fdcb6c8aa975687476d5
 mis-attributed there but corrected in
https://github.com/python/cpython/commit/bc7ea5872b0d6a1b5942260445fc768f8139c1b0

So I'm going to assume you signed the PSF contributor agreement which covers Jython too.

**Comment by clach04** [comment]
> @clach04: I notice you have a contribution to CPython [python/cpython@be55d99](https://github.com/python/cpython/commit/be55d99b3d0d289b2948fdcb6c8aa975687476d5) mis-attributed there but corrected in [python/cpython@bc7ea58](https://github.com/python/cpython/commit/bc7ea5872b0d6a1b5942260445fc768f8139c1b0)
> 
> So I'm going to assume you signed the PSF contributor agreement which covers Jython too.

Confirmed but I can't prove it. Signed it a while back for scheduler module - I'm not sure where to find the signature paperwork.

**Comment by jeff5** [comment]
I'm taking people's word for it.

**Comment by jeff5** [comment]
... and thanks for doing this @clach04 .

**Pull request merged**
