### PR TITLE
Updated ucnhash.dat to Unicode 15.1.

### PR DESCRIPTION
**Pull request by Stewori**

### CODE REVIEW

**Comment by Stewori** [comment]
Handles #344 for Unicode 15.1.

**Comment by jeff5** [comment]
What's the relationship between this and ICU4J, also in line for update under #342? Do they need to update together? Or ICU4J before the other is generated?

**Comment by Stewori** [comment]
I think that's independent. The ucnhash module does not use external API. It is a self-contained lookup based on a minimal perfect hash. It really just realizes the lookup of a unicode character by name based on data from UnicodeData.txt bundled with every official unicode release, e.g. https://www.unicode.org/Public/15.1.0/ucd/UnicodeData.txt If this update is forgotten, the only thing that happens is that the lookup does not recognize newer character names. Usually not so critical. I stumbled onto this, because I once worked out SymPy support and SymPy looked up some mathematical symbols by name and Jython's support was insufficient for SymPy (stood at unicode 3.something when there was 9.0 released). Had to figure out how to update the hash function that time. It might be that ICU features a similar API that could replace our hashing approach. So far I just did not want to touch the running system.

**Comment by jeff5** [comment]
Git is giving me a by-line on this commit, which I didn't notice it was going to do. Didn't mean to steal your thunder.

**Comment by Stewori** [comment]
NP. Don't care much about my Github reputation these days. If you want to make up for it, you can star the [APIdia repo](https://github.com/APIdia-net/apidia.net) :)

**Pull request merged**
