### PR TITLE
fix: safely compare strings using `.equals` instead of `==`

### PR DESCRIPTION
**Pull request by thetric**
Correctly compare Java Strings using `.equals()`/`switch case` instead of `==` (object identity)

### CODE REVIEW

**Comment by Stewori** [comment]
I think the `==` comparisons are actually okay because Jython is working with interned strings. Not sure how the performance impact is on this front; the comparisons are very frequently executed code. Even less sure how the trade-off is with moving to switch/case statements. That said, TBH I suspect the difference in performance would be hardly measurable at all, but it is tedious to test.

**Comment by thetric** [comment]
> I think the == comparisons are actually okay because Jython is working with interned strings.

Nice to know. On a first glance this looked like a bug to me. Do you think that this PR is still worthwhile?

**Comment by Stewori** [comment]
The style improvements look good to me, but OTOH fixing things that are not broken is unnecessary risk. I'm leaving this for @jeff5 to decide. Personally, I would accept the style improvements that are not semantic-changing (i.e. not the changed `==` comparisons) if it were a separate PR.

> looked like a bug to me

I guess with such a bug in place Jython would hardly pass a single test, probably not even startup :) . This is only about performance. OTOH I see the point that it requires to constantly educate devs and users that identifiers must be interned. Maybe the docs are not sufficiently alarming on this. Then, "OTOOH", this is fairly internal API.

**Comment by jeff5** [comment]
@thetric  Somewhat like @Stewori, I think parts of this are good and others maybe misunderstand where one is allowed to rely on a string having been interned. (It is only in certain places, but attribute look-up is one.)

The `String` case statement might be a performance improvement if there are more than a few clauses, as it is based on hash.

**Comment by thetric** [comment]
> The style improvements look good to me, but OTOH fixing things that are not broken is unnecessary risk. I'm leaving this for @jeff5 to decide. Personally, I would accept the style improvements that are not semantic-changing (i.e. not the changed == comparisons) if it were a separate PR.

Okay, I'm closing this PR and create a new one with only the stylistic changes. Thanks for your feedback :)

**Pull request closed without merging**
